# Generated by Django 5.2.4 on 2025-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'priority']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='planner_tas_user_id_09183e_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='planner_tas_user_id_446b20_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='planner_tas_user_id_892af4_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='min_block_size',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
    ]
