# Generated by Django 5.2.4 on 2025-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveIndex(
            model_name='pomodorosession',
            name='planner_pom_task_id_4cc2fd_idx',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='actual_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='planned_duration',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='session_type',
            field=models.CharField(choices=[('focus', 'Focus Session'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='focus', max_length=20),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
