# Generated by Django 5.2.4 on 2025-08-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_pomodorosession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheduled_count', models.IntegerField()),
                ('unscheduled_count', models.IntegerField()),
                ('utilization_rate', models.FloatField()),
                ('total_hours_scheduled', models.FloatField()),
                ('was_overloaded', models.BooleanField(default=False)),
                ('overload_ratio', models.FloatField(blank=True, null=True)),
                ('excess_hours', models.FloatField(blank=True, null=True)),
                ('previous_task_state', models.JSONField(help_text='JSON snapshot of task scheduling before optimization')),
                ('optimization_decisions', models.JSONField(help_text='Detailed decisions made during optimization')),
                ('recommendations', models.JSONField(default=list, help_text='Optimization recommendations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Optimization histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
