# Generated by Django 5.2.4 on 2025-08-22 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20250822_1741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_reminder_enabled', models.BooleanField(default=True)),
                ('task_reminder_minutes', models.IntegerField(default=60, help_text='Minutes before task start')),
                ('task_reminder_method', models.CharField(choices=[('browser', 'Browser Push'), ('email', 'Email'), ('both', 'Browser + Email')], default='browser', max_length=10)),
                ('deadline_warning_enabled', models.BooleanField(default=True)),
                ('deadline_warning_hours', models.IntegerField(default=24, help_text='Hours before deadline')),
                ('deadline_warning_method', models.CharField(choices=[('browser', 'Browser Push'), ('email', 'Email'), ('both', 'Browser + Email')], default='both', max_length=10)),
                ('schedule_optimization_enabled', models.BooleanField(default=True)),
                ('schedule_optimization_method', models.CharField(choices=[('browser', 'Browser Push'), ('email', 'Email'), ('both', 'Browser + Email')], default='browser', max_length=10)),
                ('pomodoro_break_enabled', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('browser_notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_reminder', 'Task Reminder'), ('deadline_warning', 'Deadline Warning'), ('schedule_optimization', 'Schedule Optimization'), ('pomodoro_break', 'Pomodoro Break')], max_length=30)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(default='browser', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='planner.task')),
            ],
            options={
                'ordering': ['-scheduled_time'],
                'indexes': [models.Index(fields=['task', 'notification_type', 'status'], name='planner_tas_task_id_235caf_idx'), models.Index(fields=['scheduled_time', 'status'], name='planner_tas_schedul_714c96_idx')],
            },
        ),
    ]
