# Generated by Django 5.2.4 on 2025-08-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_add_notification_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual Sync'), ('automatic', 'Automatic Sync'), ('webhook', 'Webhook Triggered')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('events_synced', models.IntegerField(default=0)),
                ('events_created', models.IntegerField(default=0)),
                ('events_updated', models.IntegerField(default=0)),
                ('events_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sync_duration', models.DurationField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(help_text='Primary Google Calendar ID', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sync_direction', models.CharField(choices=[('both', 'Two-way sync'), ('to_google', 'Tasks to Google only'), ('from_google', 'Google to Tasks only')], default='both', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_token', models.TextField(blank=True, help_text='Token for incremental sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True)),
                ('google_calendar_id', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('etag', models.CharField(blank=True, help_text='Google Calendar event etag for optimistic locking', max_length=255)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_event', to='planner.task')),
            ],
            options={
                'indexes': [models.Index(fields=['google_event_id'], name='planner_goo_google__c47976_idx'), models.Index(fields=['google_calendar_id'], name='planner_goo_google__e50d6a_idx')],
            },
        ),
    ]
