# Generated by Django 5.2.4 on 2025-09-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_habit_habitentry_habitmilestone'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='habit',
            new_name='planner_hab_user_id_37aa14_idx',
            old_name='planner_hab_user_id_b93a3a_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='planner_hab_user_id_098ad9_idx',
            old_name='planner_hab_user_id_dd2e5b_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='planner_hab_user_id_4beb87_idx',
            old_name='planner_hab_user_id_02a3f3_idx',
        ),
        migrations.RenameIndex(
            model_name='habitentry',
            new_name='planner_hab_habit_i_127493_idx',
            old_name='planner_hab_habit_i_bd3fe8_idx',
        ),
        migrations.RenameIndex(
            model_name='habitentry',
            new_name='planner_hab_habit_i_73e7b2_idx',
            old_name='planner_hab_habit_i_3e2a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='habitentry',
            new_name='planner_hab_date_7d5c52_idx',
            old_name='planner_hab_date_85a242_idx',
        ),
        migrations.RenameIndex(
            model_name='habitmilestone',
            new_name='planner_hab_habit_i_d47a37_idx',
            old_name='planner_hab_habit_i_89cf45_idx',
        ),
        migrations.RenameIndex(
            model_name='habitmilestone',
            new_name='planner_hab_habit_i_2bd29a_idx',
            old_name='planner_hab_habit_i_8b4c3e_idx',
        ),
    ]
