# Generated by Django 5.2.4 on 2025-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_rename_planner_hab_user_id_b93a3a_idx_planner_hab_user_id_37aa14_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the task was marked as completed', null=True),
        ),
    ]
